### ISSUE TITLE
Compiler Support for CRIU

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#16853]
- [ ] Mode Change (going from `-Xint` pre-checkpoint to `-Xjit` or `-Xaot` post-restore, and vice versa)
- [ ] Code Generation
    - [x] Generate Portable Code pre-checkpoint (https://github.com/eclipse-openj9/openj9/pull/13092)
    - [ ] `-Xrs` and -`Xtrace` (https://github.com/eclipse-openj9/openj9/issues/16839)
    - [ ] `-Xjit:enableGPU`
- [ ] Runtime
    - [ ] Options Processing Post-Restore (https://github.com/eclipse-openj9/openj9/issues/16714)
        - [ ] Update thresholds based on number of CPUs post-restore
    - [ ] Synchronize all compiler threads (compilation, sampler, iprofiler, etc.)
        - [x] Compilation Thread support (https://github.com/eclipse-openj9/openj9/pull/14331)
        - [ ] Reset `CpuUtilization`
- [ ] Performance Mode (`-Xaggressive`, `-Xtune:virtualized`, etc.)
- [ ] `-XX:[+|-]PerfTool`
- [x] JITServer
    - [x] Enable JITServer in CRIU non-portable mode (https://github.com/eclipse-openj9/openj9/pull/15674)
