### ISSUE TITLE
TriagerX - AI-Assisted Issue Triage and Assignment

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#19552]
Objective: TriagerX is a novel AI-enabled software analytics tool that we developed via the IBM CAS project (with Dr. Uddin). TriagerX aims to assign an issue to components/teams and developers and to find similar issues based on open source LLM. We would like to design and implement the workflow to serve TriagerX at Openj9. The goal is to enhance the Openj9 Project's efficiency through LLM technology, streamlining issue management and decision-making processes.

Plan:

- TriagerX model Serving Preparation: 
   - [ ] Request for a machine to serve TriagerX model
   - [ ] Deploy a trained TriagerX model with scalability and security measures (docker is preferred)

- Workflow Development: Integrate TriagerX model recommendations into issue management via GitHub workflow.
  - [ ] scan new issues
  - [ ] send API requests to the TriagerX model
  - [ ] apply TriagerX model recommendations as an issue comment

- Automation Training process (for training, we may need a machine with GPU):
   - [ ] Training Setup: Configure the machine for TriagerX model training, and automate training processes.
   - [ ] Automation Implementation: Develop scripts for automating training and deployment processes.
   - [ ] Feedback: Compare TriagerX model recommendations with the final issue assignment to validate the accurate

The TriagerX model is WIP. We are actively working on the TriagerX model to improve its accuracy and efficiency. Please don't hesitate to share any suggestions or feedback you may have regarding the project.

**Comment by llxia** [comment]
machine request: [internal issue](https://github.ibm.com/runtimes/infrastructure/issues/9390)

**Comment by hzongaro** [comment]
> Please don't hesitate to share any suggestions or feedback you may have regarding the project.

@llxia, what is the right forum to share feedback?

**Comment by LongyuZhang** [comment]
TriagerX workflow of Open Issue is working, but is missing the issue number related to it. e.g. https://github.com/eclipse-openj9/openj9/issues/19673#issuecomment-2299816976. Will add issue number into the function.
