### ISSUE TITLE
Research replace MethodHandle class with OpenJDK implementation on JDK Next

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#7352]
Research the effect of using OpenJDK MethodHandle implementation in OpenJ9, this work requires update to existing code structure inorder to satisify the dependencies.

Prototyping with following changes:

- [x] Replace **MethodType** class (#7625) 
    - Replace **MethodType** & **MethodTypeForm**
    - Update **vmconstantpool.xml** references
    - Move OpenJ9 MethodType API to new **MethodTypeHelper** class
- [x] JIT support for OpenJDK MethodType class
    - Update references to MethodType fields (#7628)
    - Fix methodDescriptor assumption (#8066)
        - Currently assmue field is initialized during MethodType creation/intern
        - New case: only initalized after first call to `MethodType.toMethodDescriptorString()`
- [x] support scanning CP during scavenges (https://github.com/eclipse/openj9/issues/7486)
- [x] support ConstantPool patching (#8460)
    - **sum.misc.Unsafe.defineAnonymousClass**
    - refer to #8396 for support non-String CP types
- [x] support MemberName (#7680)
    - Needed by:
      - **LambdaForm**
      - **MethodHandle**
      - **Invokers**
- [x] support **LambdaForm**
    - Requires:
        - **BoundMethodHandle**
        - **InvokerBytecodeGenerator**
        - **LambdaFormEditor**
- [x] separate MH resolution code into new helper class
- [x] support MHNatives.linkTo intrinsic
- [x] Add an `invokebasic` bytecode based on `@polymorphicSignature invokeBasic()` method

 
**Note:**
1. resolution approaches for MH:
    - [x] single slot result (memberName/appendix in `Object[]`) #10893 
    - [ ] double slot sturct (single resolve thread/lock on appendix slot) #10762 

**TODO:**
- Clean up of `J9VM_OPT_METHODHANDLE` flag

**Comment by pshipton** [comment]
@DanHeidinga I don't expect this will be finished for the 0.23 release, moving out.

**Comment by DanHeidinga** [comment]
Agreed.  I think the tentative target is JDK16

**Comment by babsingh** [comment]
### Update (11 Jan 21)
- **Minimal requirements** to enable OJDK MH in J9 JDK16: **JCKs should pass (strong requisite). Perf should be comparable to J9 (soft requisite).**

- Support for JITServer + OJDK MHs. Liqun will discuss with the JITServer team. Will require more time.
- JIT perf changes (early Feb 21)
- JIT functional changes (end of Jan 21)
- JIT perf testing (early Mar 21)
- VM MethodHandleNative changes (end of Jan 21)
- Functional test issues: https://github.com/eclipse/openj9/issues/11458 (end of Feb 21)
- JIT special handling. Primary plan: infer using INLs to find OJDK MH generated methods. Backup plan: tag OJDK MH generated classes.
- OJDK implementation does not satisfy Java doc, e.g. `MethodHandles.collectArguments` (Timeline: TBD)
- Other VM support: [SCC support](https://github.com/eclipse/openj9/issues/11582), [JEP358 support](https://github.com/eclipse/openj9/issues/11458#issuecomment-757020239), etc. (Timeline: TBD)

**The above dates are speculated. There is a grey area. Enabling OJDK MH for JDK16 cannot be guaranteed.** 

### Next steps

Proceed by adding minimal OpenJ9 MH support for JDK16. Simultaneously work on OJDK MH for JDK16.

**Comment by pshipton** [comment]
@fengxue-IS @babsingh @tajila since we shipped jdk17 with OpenJDK MH enbabled, it seems this should be closed. Is this still tracking anything we need to track, are we keeping it open until all versions have OpenJDK MH enabled? I'd like to at least move it forward to 0.32 unless there is something here that has to be completed for jdk18. If there is, perhaps a more specific issue is better.

**Comment by tajila** [comment]
We can make separate issues to track JDK11 and 8
